language: python
cache: pip
branches:
  only:
  - main
env:
  global:
    secure: FSpIfDEYwsgFHfxOTkdXHMYtVo/47nuNj/TVYucmEGxGOVK7EHggDZArf5UOOTa1msVtLtp43wJH5QHVbYNU77t+/I1WApJsaYVGsfeohbnHAsUOoxuUw9Scs4vVUjLgmVxzBqT8OEfirPhTrgffvgmH7DaVM+VodVG+MFkZ0oHNr/OCOpk02Ib6zSs25OVb41ymxQf5q0n+h7fdF4zD6T/3Dv3O59Y/3TZvB9dKj50wvfU+6AXZzGV8qayUfVyEk6WKskCsoGixB6JpbFBGzNqCdg7Yc9ZxYG+6PgQf1kHGOOPVIbE4Gu2shI2Amt2i02+UHXh13brgDMJwsSFJZAIMDB4GdJeeZliGPF8DMQkhU2NSl64luDYeH1a1+VjsOPXBuFIsb5yVUCRUxxkQvfUyPSk0f7cOvgcVuryN7OtiFAhMRrtwGpyoFd1O9wSiRdj7NmrLm1Mo8VjudIFVR2Mg3rwDvBMA7SBiZ7G1rZKIIT0V9CUR6rv9TsO1V4Gf7ML2YxhzsHH5q3bwGd7zv9CwwIrczctkpJQaZpI+guYjSA8PHvjyc0sm8l0AyTVsJzvGeocQgx++LoxY4WfqLnZlAAtow25wfQj5fu68xkXSwMiuK2YCzUSLkQg4nkSxCO7QdnO04EkVj48IBQIO9izumgvXNNzm+YRw6XtsfSs=
python:
- '3.8'
install:
- pip install scikit-learn
- pip install pandas
- pip install PyGithub
script:
- python test_scoring.py
before_install:
- openssl aes-256-cbc -K $encrypted_7733ca46354e_key -iv $encrypted_7733ca46354e_iv
  -in hidden_test_data.tar.enc -out hidden_test_data.tar -d
